language: go
go:
  - "1.10"

install:
  - go get github.com/jjeffery/errors
  - go get github.com/jjeffery/sqlr
  - go get github.com/aws/aws-sdk-go/...
  - go get golang.org/x/sync/errgroup

script:
  - go test -coverprofile=coverage.txt ./driver ./internal/...

after_success:
  - bash <(curl -s https://codecov.io/bash)
