language: go
go:
  - "1.10"
  - "1.9"

install:
  - go get github.com/jjeffery/errors
  - go get github.com/jjeffery/sqlr
  - go get github.com/aws/aws-sdk-go/...

script:
  - go build ./...
  - go test ./internal/parser
  # can only test the parser, because the other package tests
  # require an AWS connection

